[DOC] Add comment

diff --git a/Tools/build b/Tools/build
--- a/Tools/build
+++ b/Tools/build
@@ -16,5 +16,5 @@ cd "$(dirname "${0}")/.."
 # Swift compiler
 if check swift; then
     { if [ "${#}" -eq "0" ]; then swift build; else swift build "${@}"; fi; } 2>/dev/null \
-        | grep -Ev "^Compile " | grep -Ev "^Linking " || true
+        | grep -Ev "^Compile " | grep -Ev "^Linking " || true # for some reason grep exits with failure
 fi
